application_dir   : /home/agrathwohl/code/sacreddata/probe-parse-transcode/
analysis_logs_dir : /home/agrathwohl/code/sacreddata/probe-parse-transcode/logs/
y4m_sources       : /home/agrathwohl/code/sacreddata/probe-parse-transcode/sources/y4m/
vp8_sources       : /home/agrathwohl/code/sacreddata/probe-parse-transcode/sources/vp8/
vp9_sources       : /home/agrathwohl/code/sacreddata/probe-parse-transcode/sources/vp9/